apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::539065265448:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UKCV5DKAEKR7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::539065265448:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-02T21:25:46Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-02-02T21:25:46Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-02-03T19:41:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "208642"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 16168bb5-713a-4277-80fa-bda95baa5aeb
